---
- hosts: all
  become: true

  tasks:
    - name: Copy LAMP config
      ansible.builtin.copy:
       src: lamp-docker
       dest: /home/ec2-user/

    - name: Run the Docker-compose LAMP containers
      community.docker.docker_compose_v2:
        project_src: lamp-docker
        state: present
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
